"кот" > "код"; //true (boolean)
"2" + 2 * "2"; //24 (string)
undefined == null; //true (boolean)
undefined != null; //false (boolean)
null == 0; //false (boolean)
2 > "3"; //false (boolean)
null - false + true; //1 (number)
1 / "l"; //NaN (number>
"2" * "3"; // 6 (number)
4 + 5 + "O"; //9O (string)
"l" + 4 + 5; // 145 (string)
"4" - 2; // 2 (number)
"4" - "4x"; //NaN (number)
"23" == 23; //true (boolean)
null == false; //false (boolean)
" -4 " / 0 + 1; // -Infinity (number)
null + 1; //1 (number)
undefined + null; //NaN (number)
1 === "1"; // false (boolean)
"2" > 10; //false (boolean)
NaN == undefined; //false (boolean)
